config/routes.rb
Domreg::Application.routes.draw do
  
  root :to => 'users#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  resources :domains
  resources :users, only: [:index, :edit]
  resources :orders

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  after_commit(on: :create) do ns_balance_initialize end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :address, :city, :state,
                  :postcode, :country_id, :alternative_email, :phone, 
                  :fax, :mobile, :organization

  belongs_to :country
  belongs_to :ns_name
  has_many   :balances
  has_many   :documents
  has_many   :domains
  has_many   :orders

  validates  :first_name, :last_name, :address, :city, :state,
             :postcode, :country_id, :phone, presence: true

  validates  :email, uniqueness: true

  private
 
  def ns_balance_initialize
     @user = User.last
     NsName.create(user_id: @user.id)
     Balance.create(user_id: @user.id)
  end

end


 

app/controllers/users_controller.rb
class UsersController < ApplicationController



  # GET /users
  # GET /users.json
  def index
    @user     = User.where(email: current_user.email)
    
    @domains  = Domain.where(user_id: current_user.id)

    @ns_names = NsName.where(user_id: current_user.id)

    @balance = Balance.where(user_id: current_user.id).last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user }
    end
  end

end

app/views/users/_balance_information.html.erb
      <p>
        <b>Current balance:</b>
        <%= @balance.amount %>
      </p> 

app/views/users/_listing_domains.html.erb
<h1>Listing domains</h1>

<table>
  <tr>
    <th>DomainName</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
    <td><%= domain.name %><%= '.' + domain.domain_zone.zone_name %></td>
    <td><%= domain.domain_state.state_name %></td>
    <td><%= link_to 'Show', domain %></td>
    <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
    <td><%= link_to 'Register now', new_order_path(domain_id: domain.id) %></td>
    <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/_ns_names_information.html.erb
      <p>
        <b>NS1:</b>
        <%= @ns_names[0].ns1 %>
      </p> 
      <p>
        <b>NS2:</b>
        <%= @ns_names[0].ns2 %>
      </p> 

app/views/users/_personal_information.html.erb
      <p>
        <b>Organization:</b>
        <%= @user[0].organization %>
      </p>      <p>
        <b>Email:</b>
        <%= @user[0].email %>
      </p>
      <p>
        <b>First name:</b>
        <%= @user[0].first_name %>
      </p>
      <p>
        <b>Last name:</b>
        <%= @user[0].last_name %>
      </p>
      <p>
        <b>Address:</b>
        <%= @user[0].address %>
      </p>
      <p>
        <b>City:</b>
        <%= @user[0].city %>
      </p>
      <p>
        <b>State:</b>
        <%= @user[0].state %>
      </p>
      <p>
        <b>Postcode:</b>
        <%= @user[0].postcode %>
      </p>
      <p>
        <b>Country:</b>
        <%= @user[0].country.name %>
      </p>
      <p>
        <b>Phone:</b>
        <%= @user[0].phone %>
      </p>
      <p>
        <b>Alternative email:</b>
        <%= @user[0].alternative_email %>
      </p>
      <p>
        <b>Fax:</b>
        <%= @user[0].fax %>
      </p>
      <p>
        <b>Mobile:</b>
        <%= @user[0].mobile %>
      </p>


      <%= link_to 'Edit', edit_user_registration_path(@user) %> 

app/views/users/index.html.erb
<ul>
  <li><a href="#tabs-1">Personal account information</a></li>
  <li><a href="#tabs-2">Domains</a></li>
  <li><a href="#tabs-3">Balance</a></li>
  <li><a href="#tabs-4">Default NS names</a></li>
</ul>

  <div id="tabs-1">

    <%= render 'personal_information' %>

  </div>

  <div id="tabs-2">

    <%= render 'listing_domains' %>

  </div>

  <div id="tabs-3">

    <%= render 'balance_information' %>

  </div>

  <div id="tabs-4">

    <%= render 'ns_names_information' %>

  </div>