config/routes.rb
Domreg::Application.routes.draw do
  
  root :to => 'users#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  resources :domains
  resources :users, only: [:index, :edit]
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessible :domain_id, :user_id, :organization,
                  :first_name, :last_name, :address, :city,
                  :state, :postcode, :country_id, :alternative_email,
                  :phone, :fax, :mobile, :price, :email

  has_many        :domains  
  belongs_to      :user

  validates  :domain_id, :user_id, :first_name, :last_name, 
             :address, :city, :state, :postcode, :country_id, 
             :phone, :price, :email, presence: true  

  validates  :domain_id, uniqueness: true

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    @domain = Domain.find(@order.domain_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @user_info = User.find(current_user)

    @domain = Domain.find_by_id(params[:domain_id])
    @domain ||= Domain.find_by_id(session[:domain_id])    

    @order.first_name        = @user_info.first_name
    @order.last_name         = @user_info.last_name
    @order.organization      = @user_info.organization
    @order.address           = @user_info.address
    @order.city              = @user_info.city
    @order.state             = @user_info.state
    @order.postcode          = @user_info.email
    @order.alternative_email = @user_info.alternative_email
    @order.phone             = @user_info.phone
    @order.fax               = @user_info.fax
    @order.mobile            = @user_info.mobile
    @order.email             = @user_info.email
    @order.user_id           = @user_info.id
    @order.domain_id         = @domain.id
    @order.country_id        = @user_info.country_id
    @order.price             = @domain.domain_zone.price

    session[:domain_id] = @domain.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end


  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    @domain = Domain.find(session[:domain_id])
    @balance = Balance.where(user_id: @order.user_id).last
    rest_amount = @balance.check_balance(@order.price, @order.user_id)
    current_amount = @balance.amount

    if rest_amount != -1
      respond_to do |format|
        if @order.save
          state_id = DomainState.where(state_name: 'in progress')[0].id
          @domain.update_attribute(:domain_state_id, state_id)
          @balance_new = Balance.new(user_id: @order.user_id, amount: current_amount - @order.price)
          @balance_new.save
          @document_new = Document.new(user_id: @order.user_id, order_id: Order.last.id, amount: -@order.price)
          @document_new.save
          format.html { redirect_to domains_path, notice: 'Order was successfully created.' }
          format.json { render json: @order, status: :created, location: @order }
        else
          format.html { render action: "new" }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    
    else
    
      redirect_to new_order_path(@order), notice: 'Balance is too small for order.'

    end    
  end


end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :organization %><br />
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>  
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>  
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div> 
      <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div> 
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div> 
      <div class="field">
    <%= f.label :country_id %><br />
    <%= f.collection_select :country_id, Country.all, :id, :name, :prompt => true %>
  </div> 
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div> 
  <div class="field">
    <%= f.label :alternative_email %><br />
    <%= f.email_field :alternative_email %>
  </div> 
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div> 
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>   
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, readonly: true %>
  </div>   

  <%= f.hidden_field :user_id, value: @order.user_id %>      
  <%= f.hidden_field :domain_id, value: @order.domain_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>New order for domain <%= @domain.name + '.' + @domain.domain_zone.zone_name %></h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>